export default {
	path: "/about",
	label: "About Us",
	title: "India's Leading DPDP Act Compliance Management System",
	description: "India's trusted partner for DPDP Act compliance, combining consulting expertise with advanced compliance management software.",
	hero: {
		title: "Where Privacy Expertise Meets Automated Compliance Solutions",
		text: "Trusted partner in data protection, offering tailored compliance solutions to help businesses safeguard their data and stay ahead of regulatory challenges.",
	},
	sections: [
		{
			anchor: "who-we-are",
			type: "richText",
			heading: "Who We Are",
			html: "<p>87% of consumers will take their business elsewhere if they don't trust a company with their data. We can help you:</p><ul><li>Avoid Financial Penalties</li><li>Enhance Customer Trust and Loyalty</li><li>Improve Business Reputation</li><li>Mitigate Risks of Data Breaches</li></ul><h3>Empowering Businesses to Seamlessly Navigate Data Protection Compliance</h3><p>By prioritizing data protection and privacy, businesses can strengthen compliance and build trust with customers and stakeholders.</p><p>We understand that Data Protection and Data Privacy regulations can be complex and time-consuming for businesses. That's why we empower our clients with the skills, tools, and knowledge needed to navigate and ensure compliance with these critical regulations successfully. With our dedicated data protection consultants, including certified Privacy Compliance Consultants and Data Protection Officers, businesses can ensure comprehensive data risk mitigation. We navigate you to the evolving landscape of data protection regulations to establish a solid foundation for privacy management within your organization. We have expertise in assisting business in achieving data privacy compliance, managing customer data securely, and enhancing your overall data governance framework.</p>",
		},
		{
			anchor: "mission-vision",
			type: "richText",
			heading: "Mission and Vision",
			html: "<h3>Transforming the Complex World of Data Protection into a Seamless Journey for Organizations Privacy and Compliance</h3><h4>Mission</h4><p>Our mission is to empower businesses to navigate the complexities of data protection and privacy with confidence and ease. Through expert consulting and proprietary compliance tools, we help organizations achieve and sustain regulatory compliance while fostering a culture of security and accountability. We are committed to fostering a culture of awareness and responsibility in data security, enabling our clients to safeguard sensitive information, build consumer trust, and thrive in an ever-evolving regulatory landscape.</p><h4>Vision</h4><p>Our vision is to be the premier consulting and solutioning partner in the realm of data protection and data privacy, recognized globally for our innovative approach and cutting-edge proprietary tools. We envision a future where all organizations prioritize data privacy as a fundamental aspect of their operations, ensuring that personal information is handled with utmost care and respect. By fostering an ecosystem of trust and transparency, we aim to lead the way in shaping best practices and setting standards for data protection compliance that empower businesses to succeed responsibly in the digital age.</p>",
		},
		{
			anchor: "our-team",
			type: "team",
			eyebrow: "Our People",
			heading: "Our Team",
			intro: "Our team ensures your data privacy journey is seamless and secure.",
			items: [
				{ name: "Shilendra Sharma", role: "Founder/Principal", image: "/images/team/shilendra-sharma.webp" },
				{ name: "Kumar Priyank", role: "Co-Founder & C.E.O", image: "/images/team/kumar-priyank.webp" },
				{ name: "Abhishek Vinod Singh", role: "Advisor – Technology", image: "/images/team/abhishek-vinod-singh.webp" },
				{ name: "Sunil Khanna", role: "Senior Vice President – Technology & Product", image: "/images/team/sunil-khanna.png" },
				{ name: "Bhavna Narula", role: "Vice President - Technology & Product", image: "/images/team/bhavna-narula.png" },
				{ name: "Jaspal Singh", role: "Director - Technology & Product", image: "/images/team/jaspal-singh.png" },
				{ name: "Piush Kumar", role: "Associate Director - Technology & Product", image: "/images/team/piush-kumar.png" },
				{ name: "Audrey Saralin", role: "Senior Director – Sales", image: "/images/team/audrey-saralin.webp" },
				{ name: "Dr. Sanyam Agarwal", role: "Principal Advisor", image: "/images/team/dr-sanyam-agarwal.jpg" },
				{ name: "Gargi Rawat", role: "Director – Human Resources", image: "/images/team/gargi-rawat.webp" },
				{ name: "Muskan Singhi", role: "Senior Executive HR", image: "/images/team/muskan-singhi.jpg" },
				{ name: "Riju Ghosh", role: "Manager- Consulting and Advisory", image: "/images/team/riju-ghosh.jpg" },
				{ name: "Pawan Mishra", role: "Head of Marketing", image: "/images/team/pawan-mishra.png" },
			],
		},
		{
			anchor: "what-we-do",
			type: "features",
			eyebrow: "What We Do",
			heading: "Enabling Secure and Compliant Data Practices with Innovative Compliance Tools and Expertise",
			intro: "We provide a comprehensive suite of DPDPA compliance services, tailored to meet the unique needs of your business. Partnering with organizations of all sizes and industries, we take a personalized approach to effectively address data protection and privacy compliance challenges.",
			items: [
				{ icon: "tji-check", title: "Compliance Assessment", text: "We conduct in-depth assessments of your data processing practices to identify potential compliance gaps." },
				{ icon: "tji-organize", title: "Policy Development", text: "Our team assists in the development of robust data protection policies, ensuring they align with DPDP Act 2023 regulations." },
				{ icon: "tji-team", title: "Training and Education", text: "We offer specialized training programs designed to educate your staff on the importance of data protection and privacy, equipping them with the knowledge and skills needed for seamless DPDP Act, 2023 compliance." },
				{ icon: "tji-search", title: "Data Audit", text: "Our experts conduct data audits to help you identify and manage personal data within your organisation effectively." },
				{ icon: "tji-chart", title: "Data Protection Impact Assessments (DPIA)", text: "We guide you in conducting DPIAs to assess and mitigate the risks associated with your data processing activities." },
				{ icon: "tji-support", title: "Incident Response Planning", text: "We help you prepare for and respond to data breaches in accordance with DPDP Act 2023 requirements." },
			],
		},
		{
			anchor: "awards",
			type: "features",
			heading: "Awards & Certifications",
			intro: "Our team is proud to hold a range of industry-recognized awards and certifications that demonstrate our commitment to excellence in data privacy and compliance.",
			items: [
				{ icon: "tji-award", title: "Startup India Recognition", text: "Recognised as a startup by the Department for Promotion of Industry and Internal Trade (DPIIT), Government of India." },
				{ icon: "tji-award", title: "ICAI Northern India Regional Council", text: "Proud sponsor of ICA events 2024-2025 with the Institute of Chartered Accountants of India, Northern India Regional Council." },
				{ icon: "tji-award", title: "BFSI Technology Conclave Partnership", text: "Recognised by Express Computer for our support and partnership at the 6th BFSI Technology Conclave 2024, Pune." },
				{ icon: "tji-award", title: "Start In UP Registration", text: "Recognized as a Startup by the Department of IT & Electronics, Government of Uttar Pradesh (GoUP), through its nodal agency Uttar Pradesh Electronics Corporation Ltd. (UPLC)." },
			],
		},
		{
			type: "cta",
			heading: "Ready to Strengthen Your Data Protection Compliance?",
			text: "Book a consultation to see how our team and compliance tools can help your organisation navigate the DPDP Act with confidence.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Contact Us", href: "/contact" },
		},
	],
};
