export default {
	path: "/",
	title: "India's Best DPDP Act Compliance Management Software",
	description: "Achieve DPDP Act compliance with India's top data protection consultants using automated compliance management software.",
	hero: null,
	sections: [
		{
			type: "homeHero",
			eyebrow: "DPDP Act 2023 compliance experts",
			title: "Empowering organisations with DPDPA compliance solutions",
			highlight: "DPDPA compliance solutions",
			text: "End-to-end data protection consulting with automated compliance tools for proactive risk management.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Explore Products", href: "/products" },
			badges: ["100% Made in India Technology", "500+ Assessments", "24x7 Instant Expert Advice"],
		},
		{
			type: "marquee",
			items: [
				"Consent Management",
				"Rights & Grievance Redressal",
				"Impact Assessment",
				"DPO as a Service",
				"Third-Party Risk Assessment",
				"Cookie Consent",
				"Gap Assessment",
				"Training Programs",
			],
		},
		{
			type: "features",
			eyebrow: "Our Tools",
			numbered: true,
			heading: "Elevate Your Data Privacy Stance with Intelligent Automation",
			items: [
				{
					icon: "tji-service-1",
					title: "Consent Management",
					text: "Automates the management of Data Principal consent, handling legacy, paper and live consent with equal ease.",
					href: "/products/consent-management",
				},
				{
					icon: "tji-service-2",
					title: "Rights & Grievance Redressal",
					text: "Ensures Data Principal rights are honored with a clear mechanism for addressing complaints under the DPDP Act.",
					href: "/products/grievance-redressal",
				},
				{
					icon: "tji-service-3",
					title: "Awareness Program",
					text: "Educates employees, stakeholders and partners on safeguarding personal data and privacy best practices.",
					href: "/products/awareness-program",
				},
				{
					icon: "tji-service-4",
					title: "Impact Assessment",
					text: "Automates the DPIA process and helps stakeholders track and mitigate identified risks.",
					href: "/products/impact-assessment",
				},
				{
					icon: "tji-service-5",
					title: "Third-Party Risk Assessment",
					text: "Reviews third-party and sub-processor compliance, assessing the risk associated with the third parties.",
					href: "/products/third-party-assessment",
				},
				{
					icon: "tji-service-6",
					title: "Cookie Consent",
					text: "Captures, manages and documents user consent for website cookies in line with the DPDP Act and global privacy laws.",
					href: "/products/cookie-consent",
				},
			],
		},
		{
			type: "features",
			eyebrow: "Our Services",
			variant: "dark",
			heading: "Helping businesses navigate data privacy and compliance with ease",
			items: [
				{
					icon: "tji-check",
					title: "Gap Assessment & Readiness Review",
					text: "A detailed evaluation and expert guidance to help your business meet DPDP Act compliance requirements with minimal disruption.",
					href: "/services/gap-assessment",
				},
				{
					icon: "tji-team",
					title: "DPO as a Service",
					text: "Turns the DPDP Act's DPO requirement into a strategic advantage, strengthening your data protection framework.",
					href: "/services/dpo-as-a-service",
				},
				{
					icon: "tji-organize",
					title: "Contract Review & DPAs",
					text: "Draft and review agreements with third parties that protect personal data and uphold Data Principal rights.",
					href: "/services/contract-review",
				},
				{
					icon: "tji-strategy",
					title: "Consulting, Advisory & Audit",
					text: "Tailored policies, impact assessments, internal audit frameworks and automated privacy tools to meet DPDP Act requirements.",
					href: "/services/consulting-advisory-audit",
				},
				{
					icon: "tji-growth",
					title: "Training Programs",
					text: "Structured training with expert guidance, interactive learning and real-world case studies on DPDP Act compliance.",
					href: "/services/training-programs",
				},
				{
					icon: "tji-award",
					title: "DPDP Act Foundation Course",
					text: "A certification course building foundational expertise in digital data protection under the DPDPA.",
					href: "/services/dpdp-act-foundation-course",
				},
			],
		},
		{
			anchor: "solutions",
			type: "features",
			eyebrow: "360° Solutions",
			heading: "All-in-One, Stress-Free 360° Solutions Backed by Cutting-Edge Proprietary Tools!",
			items: [
				{ icon: "tji-check", title: "Consent Management Framework", text: "Our data protection experts will develop specific consent templates and policies tailored to the Digital Personal Data Protection Act (DPDPA) for your public-facing platforms. Key benefits: Respect for Privacy Rights; Enable a business to manage users' consent requests; Building Trust; Handling data principal access requests; Security in your compliance goals; Uniform and standardized process." },
				{ icon: "tji-chart", title: "Risk and Mitigation", text: "We assess risks related to DPDPA non-compliance and provide a comprehensive mitigation plan to address these risks. Key benefits: Ensures compliance with DPDPA to avoid penalties and legal actions; Identifies and assesses potential risks associated with data processing; Provides a structured risk mitigation plan to prevent data breaches; Strengthens overall data security posture through proactive risk management." },
				{ icon: "tji-search", title: "Processing Activity Assessments", text: "We conduct a thorough analysis of your business processes to identify gaps in your privacy framework and ensure alignment with DPDPA requirements. Key benefits: Identifies potential data privacy gaps and risks in business operations; Ensures that all data handling processes are documented, highlighting organizational accountability; Identify inefficiencies and redundancies in data handling and storage processes; Aligns processing activities with DPDPA requirements, reducing non-compliance risks." },
				{ icon: "tji-list", title: "Policy & Notice Framework Notice", text: "Our techno-legal consultants create organizational and public-facing notices that comply with the Digital Personal Data Protection Act (DPDPA) framework. Key benefits: Ensuring Transparency and Control; Protection Against Data Breaches; Prompting Data Privacy Protection Activities; Consent which serves as one of the primary legal bases for processing personal data." },
				{ icon: "tji-strategy", title: "DPIA Methodology", text: "We implement a structured procedure and methodology to conduct Data Protection Impact Assessments (DPIAs) for identified processing activities. Key benefits: Enhancing Compliance with Data Protection Laws; Identifying and Mitigating Potential Data Risks; Improving Data Management and Governance; Building trust with stakeholders." },
				{ icon: "tji-manage", title: "Principal Rights Management Procedure", text: "We will establish a process for efficiently managing and responding to principal rights requests in a timely manner. Key benefits: Establishes a clear process for managing data principal requests efficiently; Ensures timely response to data principals, improving trust and transparency; Reduces regulatory risks by maintaining compliance with rights fulfilment timelines; Streamlines internal workflows for handling rights requests; Enhances user satisfaction by facilitating smooth access to personal data rights." },
				{ icon: "tji-team", title: "Employee Awareness", text: "We offer tailored training, assessments, certifications, and compliance agreements on DPDPA for employees and key stakeholders. Key benefits: Educates employees on DPDPA requirements to minimize compliance risks; Reduces the likelihood of employee-related data breaches; Enhances data protection culture within the organization; Helps in implementing a sustainable privacy governance framework." },
				{ icon: "tji-organize", title: "Principal Rights Management Forms and Templates", text: "We will create DPDPA-compliant rights request forms and templates to facilitate easy access and exercise of rights by data principals. Key benefits: Simplifies the process for data principals to exercise their rights under DPDPA; Reduces administrative burden with pre-approved, compliant templates; Ensures consistency in responding to rights requests; Improves efficiency by standardizing documentation and workflows; Strengthens compliance readiness by ensuring correct regulatory procedures are followed." },
				{ icon: "tji-user", title: "Employee Compliance Agreement", text: "We educate your workforce to minimize liability in the event of employee non-compliance with data protection regulations. Key benefits: Provides clear guidelines on data privacy obligations, reducing ambiguity; Strengthens enforcement of data protection policies within the organization; Acts as a preventive measure against insider threats and negligence; Reduces liability by ensuring employees acknowledge their privacy responsibilities." },
				{ icon: "tji-complete", title: "Data Processing Agreement", text: "We help manage your compliance obligations with processors through vendor risk assessments and customized Data Processing Agreements. Key benefits: Legal compliance; DPA is tangible evidence of due diligence; Defines each party's responsibilities and liabilities in relation to the processing; Ensures processors only act on the data fiduciary's instructions and for the specified business purpose; Having DPDPA compliant DPAs in place helps build trust with natural persons, regulators, and business partners." },
				{ icon: "tji-worldwide", title: "Third-Party Consent Sharing and Rights Fulfilment", text: "We facilitate the sharing of explicit consent and manage rights fulfilment across your processors to ensure compliance. Key benefits: Ensures explicit consent is obtained and shared in compliance with DPDPA; Enhances transparency in third party data processing activities; Reduces legal risks by documenting consent-sharing mechanisms; Streamlines the process of fulfilling rights requests across vendors; Improves data governance and accountability in managing third party relationships." },
			],
		},
		{
			anchor: "one-stop-solution",
			type: "features",
			eyebrow: "One-stop solution",
			heading: "A 360° approach transforms complexity into simplicity, driving efficiency, compliance, and innovation",
			intro: "Cost savings, streamlined governance, faster execution, enhanced visibility, and flexible scalability, ensuring businesses stay efficient, compliant, and future-ready, all without the hassle of managing multiple vendors.",
			numbered: true,
			items: [
				{ icon: "tji-growth", title: "Cost-Effectiveness", text: "Reduce operational costs by eliminating multiple disjointed systems and inefficiencies. A unified solution means lower maintenance, fewer redundancies, and better resource utilization." },
				{ icon: "tji-organize", title: "Optimized Governance", text: "Streamline compliance, security, and risk management with an integrated governance framework that ensures transparency, accountability, and regulatory adherence." },
				{ icon: "tji-performance", title: "Faster Delivery", text: "Accelerate implementation and execution with pre-configured workflows, automation, and real-time insights, reducing delays and boosting productivity." },
				{ icon: "tji-search", title: "Greater Visibility & Coverage", text: "Gain end-to-end monitoring and control over processes, ensuring complete visibility across all functions and minimizing blind spots." },
				{ icon: "tji-process-1", title: "Scalability & Flexibility", text: "Adapt and grow effortlessly with a future-proof solution that evolves with your business needs, integrating seamlessly with new technologies and frameworks." },
			],
		},
		{
			anchor: "how-it-works",
			type: "steps",
			eyebrow: "How it works",
			heading: "Ensure compliance and enhance user trust with our expert consulting and advisory solutions",
			items: [
				{ title: "Risk Assessment", text: "We evaluate privacy practices across your organization, documenting processes, data flows, and requirements. Our assessment provides actionable strategies with clear stakeholder responsibilities." },
				{ title: "Policy Development", text: "We develop comprehensive privacy policies and procedures tailored to organization's specific needs and compliance requirements under the DPDP Act, ensuring all documentation meets regulatory standards." },
				{ title: "Compliance Tools Implementation", text: "We address organizational obligations including data governance and compliance verification before deploying automation solutions for consent management, privacy notices, and incident response." },
				{ title: "Monitoring and Auditing", text: "We establish monitoring protocols, track remediation progress, and conduct comprehensive compliance audits covering all essential privacy functions." },
				{ title: "Reporting and Documentation", text: "We maintain detailed documentation of all compliance activities, providing regular reports on compliance status, risk management progress, and emerging privacy concerns." },
				{ title: "Ongoing Support and Updates", text: "We provide continuous support to ensure your organization remains compliant with evolving regulatory requirements and privacy best practices." },
			],
		},
		{
			type: "split",
			eyebrow: "Pan India Presence",
			heading: "Seamless Compliance with Automated Privacy Tools",
			html: "<p>Your trusted partner in data protection, ensuring privacy &amp; security across every corner.</p><p><a href=\"/about\">Learn more about DPDP Consultants</a></p>",
			visual: "presence-map",
			stats: [
				{ value: "500+", label: "Assessments" },
				{ value: "100+", label: "Privacy Compliance Globally" },
				{ value: "10+", label: "Partners" },
				{ value: "24x7", label: "Instant Expert Advice" },
			],
		},
		{
			anchor: "clients",
			type: "logos",
			eyebrow: "Our Clients",
			heading: "Trusted by Leading Organisations",
			source: "clients",
		},
		{
			anchor: "testimonials",
			type: "testimonials",
			eyebrow: "Testimonials",
			heading: "What Our Clients Say",
			items: [
				{
					quote: "We engaged DPDP Consultants to assist us in implementing compliance with the Digital Personal Data Protection (DPDP) Act for our Indian entity, and the experience has been exceptional. The team at DPDP Consultants has been highly professional, responsible, and proactive throughout the engagement. Their deep understanding of the regulatory landscape, coupled with their responsiveness and structured approach, ensured a seamless compliance process. They provided valuable insights, practical solutions, and end-to-end support, making the transition smooth and efficient. We truly appreciate their commitment to excellence and would highly recommend DPDP Consultants to any organization looking for a trusted partner in data protection compliance.",
					name: "Mahalakshmi.PG, Anil A",
					role: "General Counsel",
					company: "Carl Zeiss India Pvt. Ltd.",
					logo: "/images/client-logo/zeiss_logo.png",
				},
				{
					quote: "Working with DPDP Consultants has significantly improved our digital privacy compliance. Their deep expertise in data privacy laws like DPDP, GDPR, and CCPA provided us with clear, actionable steps to meet regulatory requirements, from data collection to consent management. What stood out was their personalized approach—tailoring solutions to our business needs, making compliance seamless and stress-free. Thanks to their guidance, we’ve not only ensured compliance but also built trust with our customers by demonstrating our commitment to protecting personal information. Their service has been invaluable, and we highly recommend them for establishing a strong data privacy framework.",
					name: "Anupam Srivastav",
					role: "Director – Research and Client Services",
					company: "Mindforce Research",
					logo: "/images/client-logo/mindforce.png",
				},
				{
					quote: "Our engagement with DPDP Consultants has been instrumental in achieving data protection compliance for our organization. Their team exhibited an exceptional understanding of global privacy laws, including the DPDPA and GDPR, and their ability to translate complex legal requirements into straightforward, business-friendly solutions made the process efficient and manageable. DPDP Consultants took the time to deeply understand our business objectives and customized their approach, accordingly, providing us with the deliverables and knowledge to ensure ongoing compliance. Their proactive support instilled confidence in our team and has significantly enhanced our data privacy practices. We highly recommend DPDP Consultants for any organization seeking expert guidance in building a comprehensive data protection strategy.",
					name: "Rama Rao Salidi",
					role: "Director",
					company: "Retarget Spark",
					logo: "/images/client-logo/retarget-logo.png",
				},
				{
					quote: "We had the opportunity to partner with DPDP Consultants for our compliance journey under the Digital Personal Data Protection (DPDP) Act. From the very beginning, their team showcased exceptional professionalism and a deep understanding of both regulatory requirements and the nuances of our business operations. They provided actionable, business-aligned recommendations that seamlessly integrated into our existing workflows. What truly stood out was their structured approach and unwavering support throughout the engagement, including the timely submission of Privacy Impact Assessments for both our applications, along with all other critical deliverables. Their diligence ensured that we achieved full compliance without any disruption. We have full confidence in DPDP Consultants’ expertise and highly recommend them to any organization seeking a trusted partner in data privacy and regulatory compliance",
					name: "Shabbir Badra",
					role: "Vice President – IT & CyberSecurity",
					company: "Apraava Energy Pvt Ltd.",
					logo: "/images/client-logo/apraava.png",
				},
				{
					quote: "We are pleased to acknowledge the valuable support provided by PRIVACYIUM TECH PRIVATE LIMITED – DPDP Consultants during Tata Motors Xcelion’s Digital Personal Data Protection Act (DPDPA) assessment. Their structured approach and practical inputs supported an effective review and alignment with DPDPA requirements. We appreciate their professionalism, responsiveness, and commitment throughout the engagement.",
					name: "Ajay Wadhwa",
					role: "Chief Executive Officer",
					company: "Tata Motors Xcelion",
					logo: "/images/client-logo/motors_xcelion.png",
				},
			],
		},
		{
			type: "features",
			eyebrow: "Why Us?",
			heading: "Your trusted partner in navigating data privacy with expertise and precision",
			items: [
				{
					icon: "tji-excellence",
					title: "Expertise",
					text: "In-depth knowledge of DPDPA compliance regulations and industry best practices",
				},
				{
					icon: "tji-innovative",
					title: "Proprietary Tools",
					text: "Access to innovative, tailored tools that streamline compliance management and reduce risks",
				},
				{
					icon: "tji-strategy",
					title: "Customized Solutions",
					text: "Personalized consulting services to address your unique business needs",
				},
				{
					icon: "tji-performance",
					title: "Efficient Process",
					text: "Fast, reliable compliance solutions that save you time and resources",
				},
				{
					icon: "tji-support",
					title: "End-to-End Support",
					text: "Ongoing assistance to ensure continuous compliance and privacy protection",
				},
				{
					icon: "tji-award",
					title: "Proven Track Record",
					text: "Successful partnerships with businesses across industries, ensuring optimal outcomes",
				},
			],
		},
		{
			anchor: "partners",
			type: "logos",
			eyebrow: "Our Partners",
			heading: "Working Together with Industry Leaders",
			source: "partners",
		},
		{
			type: "cardsLinks",
			heading: "Explore More",
			items: [
				{
					title: "Blogs",
					text: "Insights, updates, and expert advice on navigating the ever-evolving world of data privacy and compliance.",
					href: "/blogs",
				},
				{
					title: "News",
					text: "The latest developments in data protection law and regulation.",
					href: "/news",
				},
				{
					title: "Webinars & Events",
					text: "Live sessions and events on DPDP Act compliance and data privacy best practices.",
					href: "/events",
				},
				{
					title: "Whitepapers & Guides",
					text: "Guides and tools to support your DPDP Act compliance journey.",
					href: "/resources",
				},
			],
		},
		{
			anchor: "faq",
			type: "faq",
			eyebrow: "FAQ",
			heading: "Frequently Asked Questions",
			items: [
				{ question: "What services does DPDP Consultants offer for data privacy and compliance?", answer: "<p>DPDP Consultants specializes in providing comprehensive services tailored to data privacy and compliance needs. Our offerings include DPDP Act Readiness Review, Data Privacy Policy Drafting, Privacy Impact Assessments, Contract Review for Data Protection Compliance, DPDP Act Compliance Assistance, and Employee Training on Data Protection Regulations. We aim to simplify the compliance journey for businesses by offering end-to-end data protection solutions.</p>" },
				{ question: "How can DPDP Consultants assist businesses in achieving DPDP Act compliance?", answer: "<p>DPDP Consultants offers expert assistance in aligning your business processes with the requirements of the Digital Personal Data Protection Act (DPDP Act) 2023. Our team conducts a thorough gap analysis, provides compliance roadmaps, and supports the implementation of privacy frameworks. With our guidance, organizations can confidently navigate complex regulatory requirements, reduce risks, and ensure seamless compliance with the DPDP Act 2023.</p>" },
				{ question: "What is the DPDP Act 2023, and why is it essential for businesses?", answer: "<p>The Digital Personal Data Protection Act 2023 is a transformative law in India focused on protecting individuals' personal data. It mandates that businesses comply with data privacy regulations, implement robust data management practices, and ensure the security of customer information. Failure to comply can result in significant penalties and reputational damage. Businesses must prioritize data privacy and adopt compliance measures to stay competitive and trustworthy.</p>" },
				{ question: "Why is data protection crucial for modern businesses?", answer: "<p>In today's digital age, data protection is a cornerstone of building customer trust and ensuring business sustainability. It helps organizations safeguard sensitive information, comply with laws like the DPDP Act 2023, and mitigate the risk of data breaches. Effective data protection enhances brand reputation, fosters customer loyalty, and ensures smooth operations in a data-driven economy.</p>" },
				{ question: "How can I contact DPDP Consultants for expert guidance on data privacy?", answer: "<p>You can connect with DPDP Consultants through multiple channels. Visit our office in Noida, Uttar Pradesh, call us at <a href=\"tel:01206930999\">0120-6930999</a>, or email us at <a href=\"mailto:info@dpdpconsultants.com\">info@dpdpconsultants.com</a>. Our team of experts is ready to assist you with your data privacy and compliance needs.</p>" },
			],
		},
		{
			type: "cta",
			heading: "Turning Compliance into Competitive Advantage",
			text: "Book a consultation to see how our consulting team and compliance tools can help your organisation meet DPDP Act requirements with confidence.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Contact Us", href: "/contact" },
		},
	],
};
