export default {
	path: "/",
	title: "India's Best DPDP Act Compliance Management Software",
	description: "Achieve DPDP Act compliance with India's top data protection consultants using automated compliance management software.",
	hero: null,
	sections: [
		{
			type: "homeHero",
			eyebrow: "DPDP Act 2023 compliance experts",
			title: "Empowering organisations with DPDPA compliance solutions",
			highlight: "DPDPA compliance solutions",
			text: "End-to-end data protection consulting with automated compliance tools for proactive risk management.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Explore Products", href: "/products" },
			badges: ["100% Made in India Technology", "500+ Assessments", "24x7 Instant Expert Advice"],
		},
		{
			type: "marquee",
			items: [
				"Consent Management",
				"Rights & Grievance Redressal",
				"Impact Assessment",
				"DPO as a Service",
				"Third-Party Risk Assessment",
				"Cookie Consent",
				"Gap Assessment",
				"Training Programs",
			],
		},
		{
			type: "features",
			eyebrow: "Our Tools",
			numbered: true,
			heading: "Elevate Your Data Privacy Stance with Intelligent Automation",
			items: [
				{
					icon: "tji-service-1",
					title: "Consent Management",
					text: "Automates the management of Data Principal consent, handling legacy, paper and live consent with equal ease.",
					href: "/products/consent-management",
				},
				{
					icon: "tji-service-2",
					title: "Rights & Grievance Redressal",
					text: "Ensures Data Principal rights are honored with a clear mechanism for addressing complaints under the DPDP Act.",
					href: "/products/grievance-redressal",
				},
				{
					icon: "tji-service-3",
					title: "Awareness Program",
					text: "Educates employees, stakeholders and partners on safeguarding personal data and privacy best practices.",
					href: "/products/awareness-program",
				},
				{
					icon: "tji-service-4",
					title: "Impact Assessment",
					text: "Automates the DPIA process and helps stakeholders track and mitigate identified risks.",
					href: "/products/impact-assessment",
				},
				{
					icon: "tji-service-5",
					title: "Third-Party Risk Assessment",
					text: "Reviews third-party and sub-processor compliance, assessing the risk associated with the third parties.",
					href: "/products/third-party-assessment",
				},
				{
					icon: "tji-service-6",
					title: "Cookie Consent",
					text: "Captures, manages and documents user consent for website cookies in line with the DPDP Act and global privacy laws.",
					href: "/products/cookie-consent",
				},
			],
		},
		{
			type: "features",
			eyebrow: "Our Services",
			variant: "dark",
			heading: "Helping businesses navigate data privacy and compliance with ease",
			items: [
				{
					icon: "tji-check",
					title: "Gap Assessment & Readiness Review",
					text: "A detailed evaluation and expert guidance to help your business meet DPDP Act compliance requirements with minimal disruption.",
					href: "/services/gap-assessment",
				},
				{
					icon: "tji-team",
					title: "DPO as a Service",
					text: "Turns the DPDP Act's DPO requirement into a strategic advantage, strengthening your data protection framework.",
					href: "/services/dpo-as-a-service",
				},
				{
					icon: "tji-organize",
					title: "Contract Review & DPAs",
					text: "Draft and review agreements with third parties that protect personal data and uphold Data Principal rights.",
					href: "/services/contract-review",
				},
				{
					icon: "tji-strategy",
					title: "Consulting, Advisory & Audit",
					text: "Tailored policies, impact assessments, internal audit frameworks and automated privacy tools to meet DPDP Act requirements.",
					href: "/services/consulting-advisory-audit",
				},
				{
					icon: "tji-growth",
					title: "Training Programs",
					text: "Structured training with expert guidance, interactive learning and real-world case studies on DPDP Act compliance.",
					href: "/services/training-programs",
				},
				{
					icon: "tji-award",
					title: "DPDP Act Foundation Course",
					text: "A certification course building foundational expertise in digital data protection under the DPDPA.",
					href: "/services/dpdp-act-foundation-course",
				},
			],
		},
		{
			type: "split",
			eyebrow: "Pan India Presence",
			heading: "Seamless Compliance with Automated Privacy Tools",
			html: "<p>Your trusted partner in data protection, ensuring privacy &amp; security across every corner.</p><p><a href=\"/about\">Learn more about DPDP Consultants</a></p>",
			visual: "presence-map",
			stats: [
				{ value: "500+", label: "Assessments" },
				{ value: "100+", label: "Privacy Compliance Globally" },
				{ value: "10+", label: "Partners" },
				{ value: "24x7", label: "Instant Expert Advice" },
			],
		},
		{
			type: "logos",
			eyebrow: "Our Clients",
			heading: "Trusted by Leading Organisations",
			source: "clients",
		},
		{
			type: "features",
			eyebrow: "Why Us?",
			heading: "Your trusted partner in navigating data privacy with expertise and precision",
			items: [
				{
					icon: "tji-excellence",
					title: "Expertise",
					text: "In-depth knowledge of DPDPA compliance regulations and industry best practices",
				},
				{
					icon: "tji-innovative",
					title: "Proprietary Tools",
					text: "Access to innovative, tailored tools that streamline compliance management and reduce risks",
				},
				{
					icon: "tji-strategy",
					title: "Customized Solutions",
					text: "Personalized consulting services to address your unique business needs",
				},
				{
					icon: "tji-performance",
					title: "Efficient Process",
					text: "Fast, reliable compliance solutions that save you time and resources",
				},
				{
					icon: "tji-support",
					title: "End-to-End Support",
					text: "Ongoing assistance to ensure continuous compliance and privacy protection",
				},
				{
					icon: "tji-award",
					title: "Proven Track Record",
					text: "Successful partnerships with businesses across industries, ensuring optimal outcomes",
				},
			],
		},
		{
			type: "logos",
			eyebrow: "Our Partners",
			heading: "Working Together with Industry Leaders",
			source: "partners",
		},
		{
			type: "cardsLinks",
			heading: "Explore More",
			items: [
				{
					title: "Blogs",
					text: "Insights, updates, and expert advice on navigating the ever-evolving world of data privacy and compliance.",
					href: "/blogs",
				},
				{
					title: "News",
					text: "The latest developments in data protection law and regulation.",
					href: "/news",
				},
				{
					title: "Webinars & Events",
					text: "Live sessions and events on DPDP Act compliance and data privacy best practices.",
					href: "/events",
				},
				{
					title: "Whitepapers & Guides",
					text: "Guides and tools to support your DPDP Act compliance journey.",
					href: "/resources",
				},
			],
		},
		{
			type: "cta",
			heading: "Turning Compliance into Competitive Advantage",
			text: "Book a consultation to see how our consulting team and compliance tools can help your organisation meet DPDP Act requirements with confidence.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Contact Us", href: "/contact" },
		},
	],
};
