export default {
	path: "/",
	title: "India's Best DPDP Act Compliance Management Software",
	description: "Achieve DPDP Act compliance with India's top data protection consultants using automated compliance management software.",
	hero: null,
	sections: [
		{
			type: "homeHero",
			eyebrow: "DPDP Act 2023 compliance experts",
			title: "Empowering organisations with DPDPA compliance solutions",
			highlight: "DPDPA compliance solutions",
			text: "End-to-end data protection consulting with automated compliance tools for proactive risk management.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Explore Products", href: "/products" },
			badges: ["100% Made in India Technology", "500+ Assessments", "24x7 Instant Expert Advice"],
		},
		{
			type: "marquee",
			items: [
				"Consent Management",
				"Rights & Grievance Redressal",
				"Impact Assessment",
				"DPO as a Service",
				"Third-Party Risk Assessment",
				"Cookie Consent",
				"Gap Assessment",
				"Training Programs",
			],
		},
		{
			type: "features",
			eyebrow: "Our Tools",
			numbered: true,
			heading: "Elevate Your Data Privacy Stance with Intelligent Automation",
			items: [
				{
					icon: "tji-service-1",
					title: "Consent Management",
					text: "Automates the management of Data Principal consent, handling legacy, paper and live consent with equal ease.",
					href: "/products/consent-management",
				},
				{
					icon: "tji-service-2",
					title: "Rights & Grievance Redressal",
					text: "Ensures Data Principal rights are honored with a clear mechanism for addressing complaints under the DPDP Act.",
					href: "/products/grievance-redressal",
				},
				{
					icon: "tji-service-3",
					title: "Awareness Program",
					text: "Educates employees, stakeholders and partners on safeguarding personal data and privacy best practices.",
					href: "/products/awareness-program",
				},
				{
					icon: "tji-service-4",
					title: "Impact Assessment",
					text: "Automates the DPIA process and helps stakeholders track and mitigate identified risks.",
					href: "/products/impact-assessment",
				},
				{
					icon: "tji-service-5",
					title: "Third-Party Risk Assessment",
					text: "Reviews third-party and sub-processor compliance, assessing the risk associated with the third parties.",
					href: "/products/third-party-assessment",
				},
				{
					icon: "tji-service-6",
					title: "Cookie Consent",
					text: "Captures, manages and documents user consent for website cookies in line with the DPDP Act and global privacy laws.",
					href: "/products/cookie-consent",
				},
			],
		},
		{
			type: "features",
			eyebrow: "Our Services",
			variant: "dark",
			heading: "Helping businesses navigate data privacy and compliance with ease",
			items: [
				{
					icon: "tji-check",
					title: "Gap Assessment & Readiness Review",
					text: "A detailed evaluation and expert guidance to help your business meet DPDP Act compliance requirements with minimal disruption.",
					href: "/services/gap-assessment",
				},
				{
					icon: "tji-team",
					title: "DPO as a Service",
					text: "Turns the DPDP Act's DPO requirement into a strategic advantage, strengthening your data protection framework.",
					href: "/services/dpo-as-a-service",
				},
				{
					icon: "tji-organize",
					title: "Contract Review & DPAs",
					text: "Draft and review agreements with third parties that protect personal data and uphold Data Principal rights.",
					href: "/services/contract-review",
				},
				{
					icon: "tji-strategy",
					title: "Consulting, Advisory & Audit",
					text: "Tailored policies, impact assessments, internal audit frameworks and automated privacy tools to meet DPDP Act requirements.",
					href: "/services/consulting-advisory-audit",
				},
				{
					icon: "tji-growth",
					title: "Training Programs",
					text: "Structured training with expert guidance, interactive learning and real-world case studies on DPDP Act compliance.",
					href: "/services/training-programs",
				},
				{
					icon: "tji-award",
					title: "DPDP Act Foundation Course",
					text: "A certification course building foundational expertise in digital data protection under the DPDPA.",
					href: "/services/dpdp-act-foundation-course",
				},
			],
		},
		{
			type: "split",
			eyebrow: "Pan India Presence",
			heading: "Seamless Compliance with Automated Privacy Tools",
			html: "<p>Your trusted partner in data protection, ensuring privacy &amp; security across every corner.</p><p><a href=\"/about\">Learn more about DPDP Consultants</a></p>",
			visual: "presence-map",
			stats: [
				{ value: "500+", label: "Assessments" },
				{ value: "100+", label: "Privacy Compliance Globally" },
				{ value: "10+", label: "Partners" },
				{ value: "24x7", label: "Instant Expert Advice" },
			],
		},
		{
			anchor: "clients",
			type: "logos",
			eyebrow: "Our Clients",
			heading: "Trusted by Leading Organisations",
			source: "clients",
		},
		{
			anchor: "testimonials",
			type: "testimonials",
			eyebrow: "Testimonials",
			heading: "What Our Clients Say",
			items: [
				{
					quote: "We engaged DPDP Consultants to assist us in implementing compliance with the Digital Personal Data Protection (DPDP) Act for our Indian entity, and the experience has been exceptional. The team at DPDP Consultants has been highly professional, responsible, and proactive throughout the engagement. Their deep understanding of the regulatory landscape, coupled with their responsiveness and structured approach, ensured a seamless compliance process. They provided valuable insights, practical solutions, and end-to-end support, making the transition smooth and efficient. We truly appreciate their commitment to excellence and would highly recommend DPDP Consultants to any organization looking for a trusted partner in data protection compliance.",
					name: "Mahalakshmi.PG, Anil A",
					role: "General Counsel",
					company: "Carl Zeiss India Pvt. Ltd.",
					logo: "/images/client-logo/zeiss_logo.png",
				},
				{
					quote: "Working with DPDP Consultants has significantly improved our digital privacy compliance. Their deep expertise in data privacy laws like DPDP, GDPR, and CCPA provided us with clear, actionable steps to meet regulatory requirements, from data collection to consent management. What stood out was their personalized approach—tailoring solutions to our business needs, making compliance seamless and stress-free. Thanks to their guidance, we’ve not only ensured compliance but also built trust with our customers by demonstrating our commitment to protecting personal information. Their service has been invaluable, and we highly recommend them for establishing a strong data privacy framework.",
					name: "Anupam Srivastav",
					role: "Director – Research and Client Services",
					company: "Mindforce Research",
					logo: "/images/client-logo/mindforce.png",
				},
				{
					quote: "Our engagement with DPDP Consultants has been instrumental in achieving data protection compliance for our organization. Their team exhibited an exceptional understanding of global privacy laws, including the DPDPA and GDPR, and their ability to translate complex legal requirements into straightforward, business-friendly solutions made the process efficient and manageable. DPDP Consultants took the time to deeply understand our business objectives and customized their approach, accordingly, providing us with the deliverables and knowledge to ensure ongoing compliance. Their proactive support instilled confidence in our team and has significantly enhanced our data privacy practices. We highly recommend DPDP Consultants for any organization seeking expert guidance in building a comprehensive data protection strategy.",
					name: "Rama Rao Salidi",
					role: "Director",
					company: "Retarget Spark",
					logo: "/images/client-logo/retarget-logo.png",
				},
				{
					quote: "We had the opportunity to partner with DPDP Consultants for our compliance journey under the Digital Personal Data Protection (DPDP) Act. From the very beginning, their team showcased exceptional professionalism and a deep understanding of both regulatory requirements and the nuances of our business operations. They provided actionable, business-aligned recommendations that seamlessly integrated into our existing workflows. What truly stood out was their structured approach and unwavering support throughout the engagement, including the timely submission of Privacy Impact Assessments for both our applications, along with all other critical deliverables. Their diligence ensured that we achieved full compliance without any disruption. We have full confidence in DPDP Consultants’ expertise and highly recommend them to any organization seeking a trusted partner in data privacy and regulatory compliance",
					name: "Shabbir Badra",
					role: "Vice President – IT & CyberSecurity",
					company: "Apraava Energy Pvt Ltd.",
					logo: "/images/client-logo/apraava.png",
				},
				{
					quote: "We are pleased to acknowledge the valuable support provided by PRIVACYIUM TECH PRIVATE LIMITED – DPDP Consultants during Tata Motors Xcelion’s Digital Personal Data Protection Act (DPDPA) assessment. Their structured approach and practical inputs supported an effective review and alignment with DPDPA requirements. We appreciate their professionalism, responsiveness, and commitment throughout the engagement.",
					name: "Ajay Wadhwa",
					role: "Chief Executive Officer",
					company: "Tata Motors Xcelion",
					logo: "/images/client-logo/motors_xcelion.png",
				},
			],
		},
		{
			type: "features",
			eyebrow: "Why Us?",
			heading: "Your trusted partner in navigating data privacy with expertise and precision",
			items: [
				{
					icon: "tji-excellence",
					title: "Expertise",
					text: "In-depth knowledge of DPDPA compliance regulations and industry best practices",
				},
				{
					icon: "tji-innovative",
					title: "Proprietary Tools",
					text: "Access to innovative, tailored tools that streamline compliance management and reduce risks",
				},
				{
					icon: "tji-strategy",
					title: "Customized Solutions",
					text: "Personalized consulting services to address your unique business needs",
				},
				{
					icon: "tji-performance",
					title: "Efficient Process",
					text: "Fast, reliable compliance solutions that save you time and resources",
				},
				{
					icon: "tji-support",
					title: "End-to-End Support",
					text: "Ongoing assistance to ensure continuous compliance and privacy protection",
				},
				{
					icon: "tji-award",
					title: "Proven Track Record",
					text: "Successful partnerships with businesses across industries, ensuring optimal outcomes",
				},
			],
		},
		{
			anchor: "partners",
			type: "logos",
			eyebrow: "Our Partners",
			heading: "Working Together with Industry Leaders",
			source: "partners",
		},
		{
			type: "cardsLinks",
			heading: "Explore More",
			items: [
				{
					title: "Blogs",
					text: "Insights, updates, and expert advice on navigating the ever-evolving world of data privacy and compliance.",
					href: "/blogs",
				},
				{
					title: "News",
					text: "The latest developments in data protection law and regulation.",
					href: "/news",
				},
				{
					title: "Webinars & Events",
					text: "Live sessions and events on DPDP Act compliance and data privacy best practices.",
					href: "/events",
				},
				{
					title: "Whitepapers & Guides",
					text: "Guides and tools to support your DPDP Act compliance journey.",
					href: "/resources",
				},
			],
		},
		{
			type: "cta",
			heading: "Turning Compliance into Competitive Advantage",
			text: "Book a consultation to see how our consulting team and compliance tools can help your organisation meet DPDP Act requirements with confidence.",
			primary: { label: "Book a Consultation", href: "/book-consultation" },
			secondary: { label: "Contact Us", href: "/contact" },
		},
	],
};
