// Permanent (301) redirects from the old PHP website's public addresses to
// the new pages, so search rankings and bookmarks carry over. Loaded by
// next.config.js; validate.test.js checks every destination is a real page.
//
// Old addresses come from the old site's menus, footer, llms.txt and page
// files (drafts/backups such as index-08may.php were never linked and are
// left out). Rules with `query` match only when that query value is present
// and must come before the plain rule for the same file.

// Each old blog post (blog.php?id=N&title=...) to its migrated post. The
// list is generated by the old-blog migration (backend/prisma/data).
const OLD_BLOG_POSTS = require("./oldBlogRedirects.json");
// Each old newsletter article (newsletter.php?id=N&title=...) to its migrated
// News page (backend/prisma/data/old-site-newsletters.json).
const OLD_NEWSLETTERS = require("./oldNewsletterRedirects.json");

const SITE_REDIRECTS = [
	...OLD_BLOG_POSTS.map(post => ({ from: "/blog.php", query: { id: String(post.id) }, to: `/blogs/${post.slug}` })),
	...OLD_NEWSLETTERS.map(item => ({ from: "/newsletter.php", query: { id: String(item.id) }, to: `/news/${item.slug}` })),

	// Contact forms that the old site opened with ?act=...
	{ from: "/contact.php", query: { act: "newsletter" }, to: "/subscribe" },
	{ from: "/contact.php", query: { act: "schedule" }, to: "/book-consultation" },
	{ from: "/contact.php", query: { act: "whitepapers" }, to: "/resources?type=whitepaper" },
	{ from: "/contact.php", query: { act: "research" }, to: "/resources?type=report" },
	{ from: "/contact-us.php", query: { act: "schedule" }, to: "/book-consultation" },
	{ from: "/contact-us.php", query: { act: "newsletter" }, to: "/subscribe" },

	// Home and company
	{ from: "/index.php", to: "/" },
	{ from: "/about-us.php", to: "/about" },
	{ from: "/our-team.php", to: "/about#our-team" },
	{ from: "/clients.php", to: "/#clients" },
	{ from: "/our-partners.php", to: "/#partners" },
	{ from: "/partner.php", to: "/partner-with-us" },
	{ from: "/case-study.php", to: "/case-studies" },
	{ from: "/faq.php", to: "/faq" },
	{ from: "/contact.php", to: "/contact" },
	{ from: "/contact-us.php", to: "/contact" },
	{ from: "/thanks.php", to: "/thank-you" },
	{ from: "/thankyou.php", to: "/thank-you" },

	// DPDP Act 2023
	{ from: "/what-is-dpdpa.php", to: "/dpdp-act" },
	{ from: "/draft-dpdp-rules-2025.php", to: "/dpdp-act/dpdp-rules-2025" },
	{ from: "/dpdp-act-2025.php", to: "/dpdp-act/dpdp-rules-2025" },
	{ from: "/administrative-fines-and-penalties.php", to: "/dpdp-act/penalties-and-fines" },
	{ from: "/subcontractor-and-thrid-party-issues.php", to: "/dpdp-act/third-party-obligations" },
	{ from: "/dpdpa-and-business-discontiniuity.php", to: "/dpdp-act/business-continuity" },

	// Compliance tools
	{ from: "/compliance-tools.php", to: "/products" },
	{ from: "/dpdpa-tools.php", to: "/products" },
	{ from: "/tools.php", to: "/products" },
	{ from: "/dpcm.php", to: "/products/consent-management" },
	{ from: "/data-principal-consent-management.php", to: "/products/consent-management" },
	{ from: "/dpgr.php", to: "/products/grievance-redressal" },
	{ from: "/data-principal-rights-and-grievance-redressal.php", to: "/products/grievance-redressal" },
	{ from: "/dpap.php", to: "/products/awareness-program" },
	{ from: "/data-protection-awareness-program.php", to: "/products/awareness-program" },
	{ from: "/dpia.php", to: "/products/impact-assessment" },
	{ from: "/data-protection-impact-assessment.php", to: "/products/impact-assessment" },
	{ from: "/dptpa.php", to: "/products/third-party-assessment" },
	{ from: "/data-protection-third-party-assessment.php", to: "/products/third-party-assessment" },
	{ from: "/cookie-consent-management.php", to: "/products/cookie-consent" },
	{ from: "/cookie_consent.php", to: "/products/cookie-consent" },

	// Services
	{ from: "/services.php", to: "/services" },
	{ from: "/our-service.php", to: "/services" },
	{ from: "/readiness-review.php", to: "/services/gap-assessment" },
	{ from: "/dpdpa-readiness-review.php", to: "/services/gap-assessment" },
	{ from: "/gap-assessment-form.php", to: "/services/gap-assessment" },
	{ from: "/gap-assessment-questions.php", to: "/services/gap-assessment" },
	{ from: "/gap-assessment-scorecard.php", to: "/services/gap-assessment" },
	{ from: "/consulting-advisory-and-audit.php", to: "/services/consulting-advisory-audit" },
	{ from: "/dpdpa-compliance-assistance.php", to: "/services/consulting-advisory-audit" },
	{ from: "/data-protection-officer-as-a-service.php", to: "/services/dpo-as-a-service" },
	{ from: "/data-protection-officer-services.php", to: "/services/dpo-as-a-service" },
	{ from: "/contract-review-data-processing-agreements.php", to: "/services/contract-review" },
	{ from: "/contract-review.php", to: "/services/contract-review" },
	{ from: "/training-programs-for-DPDPA-compliance.php", to: "/services/training-programs" },
	{ from: "/dpdpa-training.php", to: "/services/training-programs" },
	{ from: "/dpdp-act-foundation-course.php", to: "/services/dpdp-act-foundation-course" },
	{ from: "/course-form.php", to: "/services/dpdp-act-foundation-course" },

	// Resources
	{ from: "/blog.php", to: "/blogs" },
	{ from: "/blogs.php", to: "/blogs" },
	{ from: "/vlogs.php", to: "/blogs" },
	{ from: "/inthenews.php", to: "/news" },
	{ from: "/pr.php", to: "/news" },
	{ from: "/events.php", to: "/events" },
	{ from: "/webinars.php", to: "/events?when=past" },
	{ from: "/whitepaper.php", to: "/resources?type=whitepaper" },
	{ from: "/whitepapers.php", to: "/resources?type=whitepaper" },
	{ from: "/research.php", to: "/resources?type=report" },
	{ from: "/research-report.php", to: "/resources?type=report" },
	// The newsletter articles now live in News; sign-up stays at /subscribe.
	{ from: "/newsletter.php", to: "/news" },
	{ from: "/newsletters.php", to: "/news" },

	// Careers (one old page per job opening)
	{ from: "/career.php", to: "/careers" },
	{ from: "/api-integration-specialist.php", to: "/careers" },
	{ from: "/chief-compliance-officer.php", to: "/careers" },
	{ from: "/compliance-sales-associate.php", to: "/careers" },
	{ from: "/dpdpa-Specialists.php", to: "/careers" },
	{ from: "/hr-and-marketing-executive.php", to: "/careers" },
	{ from: "/postgreSQL-database-administrator.php", to: "/careers" },
	{ from: "/sales-manager.php", to: "/careers" },
	{ from: "/senior-functional-Implementation-consultant.php", to: "/careers" },
	{ from: "/senior-python-engineer.php", to: "/careers" },
	{ from: "/senior-technical-consultant-architect.php", to: "/careers" },

	// Legal
	{ from: "/privacyium-privacy-policy.php", to: "/privacy-notice" },
	{ from: "/terms-and-conditions.php", to: "/terms-and-conditions" },
];

// Next.js redirects() format.
function toNextRedirects(rules = SITE_REDIRECTS) {
	return rules.map(rule => ({
		source: rule.from,
		destination: rule.to,
		permanent: true,
		...(rule.query
			? { has: Object.entries(rule.query).map(([key, value]) => ({ type: "query", key, value })) }
			: {}),
	}));
}

module.exports = { SITE_REDIRECTS, toNextRedirects };
